import 'quote.dart';

final List<Quote> quotes = [
  Quote(
    text: "The only limit to our realization of tomorrow is our doubts of today.",
    author: "Franklin D. Roosevelt",
    category: "Motivational",
    details: "Franklin D. Roosevelt, the 32nd President of the United States (1933-1945), led the country through the Great Depression and World War II. This quote from his first inaugural address emphasizes the power of belief and the importance of overcoming self-doubt to achieve success in the future. Roosevelt himself overcame personal adversity after contracting polio in 1921, which left him paralyzed from the waist down. Despite this challenge, he went on to become one of America's most influential presidents, implementing the New Deal programs that helped recover the economy during the Great Depression.",
    image: "assets/roosevelt_fdr.jpg",
  ),
  Quote(
    text: "Believe you can and you're halfway there.",
    author: "Theodore Roosevelt",
    category: "Inspirational",
    details: "Theodore Roosevelt, the 26th President of the United States (1901-1909), was known for his resilience, adventurous spirit, and determination. This quote highlights the significance of self-belief in achieving one's goals. Roosevelt exemplified this philosophy throughout his life, overcoming childhood asthma to become a renowned outdoorsman, Rough Rider, and eventually President. His 'strenuous life' philosophy emphasized the importance of effort and perseverance in all endeavors, making him a symbol of American grit and optimism.",
    image: "assets/roosevelt_theodore.jpg",
  ),
  Quote(
    text: "Do what you can, with what you have, where you are.",
    author: "Theodore Roosevelt",
    category: "Life",
    details: "This powerful quote by Theodore Roosevelt encourages resourcefulness and resilience in the face of limitations. Roosevelt believed that waiting for ideal circumstances often leads to inaction and missed opportunities. Instead, he advocated for making the best of any situation and using available resources to move forward. This philosophy guided his approach to conservation, politics, and personal challenges. Roosevelt applied this principle during his famous Amazon expedition in 1913-1914, where the team had to adapt to extremely challenging conditions with limited supplies. This quote reminds us that circumstances are rarely perfect, but action and adaptability can lead to progress regardless.",
    image: "assets/roosevelt_theodore.jpg",
  ),
  Quote(
    text: "Success is not final, failure is not fatal: It is the courage to continue that counts.",
    author: "Winston Churchill",
    category: "Success",
    details: "Winston Churchill, the British Prime Minister during World War II (1940-1945, 1951-1955), was known for his resilience and powerful oratory. This quote embodies Churchill's life philosophy, which was tested during Britain's darkest hours of WWII. Churchill faced numerous setbacks throughout his career – including the disastrous Gallipoli Campaign in WWI and political wilderness years in the 1930s – before becoming Prime Minister at age 65. His leadership during the Battle of Britain and throughout WWII exemplified the perseverance this quote celebrates. Churchill understood that both triumph and defeat are temporary states, and true character is revealed in how one responds to changing fortunes.",
    image: "assets/churchill.jpeg",
  ),
  Quote(
    text: "Life is 10% what happens to us and 90% how we react to it.",
    author: "Charles R. Swindoll",
    category: "Life",
    details: "Charles R. Swindoll, a renowned Christian pastor, author, and educator born in 1934, emphasizes the transformative power of attitude in this quote. Drawing from decades of pastoral counseling and life observation, Swindoll articulates a profound truth about human experience: while external circumstances are often beyond our control, our response to those circumstances shapes our reality far more significantly. This insight has resonated with millions through his radio program 'Insight for Living,' broadcast in over 2,000 outlets worldwide. Swindoll's perspective encourages personal responsibility and mindfulness about how our reactions and attitudes determine our experience of life's challenges and opportunities.",
    image: "assets/swindoll.jpeg",
  ),
  Quote(
    text: "Happiness depends upon ourselves.",
    author: "Aristotle",
    category: "Philosophy",
    details: "Aristotle (384-322 BCE), the Greek philosopher and student of Plato, developed this concept as part of his Nicomachean Ethics, where he explored the nature of eudaimonia (often translated as happiness or well-being). Unlike modern conceptions that might equate happiness with momentary pleasure, Aristotle's view was more comprehensive. He believed that true happiness (eudaimonia) comes from living virtuously and developing one's potential to the fullest. This requires deliberate cultivation of character, ethical wisdom, and meaningful relationships. For Aristotle, happiness wasn't passive or granted from external sources, but actively achieved through rational choice, moral virtue, and intellectual contemplation. This ancient wisdom continues to influence modern positive psychology and ethical philosophy.",
    image: "assets/aristotle.jpg",
  ),
  Quote(
    text: "It does not matter how slowly you go as long as you do not stop.",
    author: "Confucius",
    category: "Motivational",
    details: "Confucius (551-479 BCE), one of the most influential Chinese philosophers, emphasized the value of persistence and continuous improvement in his teachings. This quote reflects his belief in the power of steady progress, regardless of speed. In Confucian philosophy, learning and self-cultivation were lifelong pursuits that required patience and perseverance. The Analects, a collection of his sayings, frequently returns to themes of diligence and determination. This quote has particular significance in Eastern cultures that traditionally value long-term thinking and gradual mastery. Confucius taught that even slow progress accumulates over time, and the consistency of effort matters more than the rate of advancement. This wisdom remains relevant for modern challenges requiring sustained effort, from education to personal development.",
    image: "assets/confucius.jpg",
  ),
  Quote(
    text: "The best way to predict the future is to create it.",
    author: "Peter Drucker",
    category: "Success",
    details: "Peter Drucker (1909-2005), widely considered the father of modern management theory, revolutionized organizational thinking in the 20th century. This quote encapsulates his forward-thinking approach to business and life. Born in Austria and later immigrating to the United States, Drucker wrote 39 books and countless articles on management, innovation, and social change. He emphasized the importance of proactive leadership and strategic planning rather than passive reaction to events. Drucker advised corporations, non-profits, and governments alike, consistently advocating for organizations to shape their destinies through innovation and deliberate action. His concept of 'knowledge workers' anticipated the information economy decades before it emerged. This quote reminds us that rather than merely anticipating trends, we can actively participate in creating the future through intentional choices and innovation.",
    image: "assets/drucker.jpeg",
  ),
  Quote(
    text: "We are what we repeatedly do. Excellence, then, is not an act, but a habit.",
    author: "Aristotle",
    category: "Philosophy",
    details: "This profound statement captures the essence of Aristotle's virtue ethics. While often attributed directly to Aristotle, it was actually written by Will Durant in 'The Story of Philosophy' (1926) as an interpretation of Aristotle's Nicomachean Ethics. Nevertheless, it accurately reflects Aristotle's teaching that virtues develop through practice and repetition until they become second nature. For Aristotle, excellence (aretē in Greek) wasn't achieved through isolated moments of brilliance but through consistent, habitual action that shapes character over time. This concept forms the foundation of his ethical system, where moral virtue comes from habituation—repeating virtuous actions until they become ingrained in one's character. Modern psychology and habit formation theories continue to validate this ancient wisdom, recognizing that our daily routines ultimately define who we become.",
    image: "assets/aristotle.jpg",
  ),
  Quote(
    text: "To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment.",
    author: "Ralph Waldo Emerson",
    category: "Life",
    details: "Ralph Waldo Emerson (1803-1882), the influential American essayist, poet, and leader of the Transcendentalist movement, championed the philosophy of individualism and self-reliance throughout his work. This quote comes from his essay 'Self-Reliance' (1841), which argues for trusting one's inner voice above societal expectations. Emerson lived during a time of significant social conformity and conventional thinking in America, making his call for authentic self-expression particularly revolutionary. His philosophy influenced generations of thinkers, writers, and social reformers, including Henry David Thoreau, Walt Whitman, and later civil rights activists. The quote speaks to the universal human struggle between authenticity and conformity, suggesting that maintaining one's true nature despite external pressures represents a profound form of courage and achievement.",
    image: "assets/emerson.jpeg",
  ),
  Quote(
    text: "An investment in knowledge pays the best interest.",
    author: "Benjamin Franklin",
    category: "Education",
    details: "Benjamin Franklin (1706-1790) was one of the Founding Fathers of the United States and a polymath whose contributions spanned politics, science, invention, and literature. This quote reflects Franklin's lifelong commitment to education and self-improvement. Despite having only two years of formal schooling, Franklin became one of the most learned individuals of his era through relentless self-education. He established the first public lending library in America, founded the University of Pennsylvania, and constantly sought to expand his knowledge through reading, experimentation, and correspondence with leading thinkers worldwide. Franklin's Poor Richard's Almanack, published annually from 1732 to 1758, popularized many such wisdom-filled sayings. His life exemplified the value of continuous learning and how intellectual development compounds over time, much like financial interest.",
    image: "assets/franklin.jpeg",
  ),
  Quote(
    text: "Injustice anywhere is a threat to justice everywhere.",
    author: "Martin Luther King Jr.",
    category: "Justice",
    details: "Dr. Martin Luther King Jr. (1929-1968) wrote this powerful statement in his 'Letter from Birmingham Jail' on April 16, 1963. The letter was composed during King's imprisonment for participating in nonviolent protests against racial segregation in Birmingham, Alabama. Written in response to white clergymen who criticized his activism as 'unwise and untimely,' this letter became one of the most important documents of the Civil Rights Movement. Through these words, King articulated the interconnected nature of justice and human rights, arguing that oppression cannot be compartmentalized or ignored simply because it occurs elsewhere or affects others. This philosophy underpinned King's approach to civil rights as a universal human issue rather than merely a regional or racial concern. The quote continues to inspire social justice movements worldwide, reminding us that the struggle for justice transcends geographical, cultural, and political boundaries.",
    image: "assets/Martin.jpg",
  ),
  Quote(
    text: "The only thing we have to fear is fear itself.",
    author: "Franklin D. Roosevelt",
    category: "Motivational",
    details: "This iconic quote comes from Franklin D. Roosevelt's first inaugural address, delivered on March 4, 1933, during the depths of the Great Depression. With unemployment at 25% and the banking system on the verge of collapse, Roosevelt faced a nation paralyzed by economic fear and uncertainty. The full context adds even more power to the quote: 'Let me assert my firm belief that the only thing we have to fear is fear itself—nameless, unreasoning, unjustified terror which paralyzes needed efforts to convert retreat into advance.' Roosevelt understood that collective panic and hopelessness were themselves obstacles to recovery. Throughout his presidency (1933-1945), he would continue to address the nation through 'fireside chats,' using radio to restore confidence and explain complex policies. This quote has transcended its original context to become a timeless reminder about how fear can be more debilitating than the challenges we actually face.",
    image: "assets/roosevelt_fdr.jpg",
  ),
  Quote(
    text: "Opportunities don't happen. You create them.",
    author: "Chris Grosser",
    category: "Success",
    details: "Chris Grosser, a contemporary entrepreneur and photographer, captures a fundamental principle of proactive success with this quote. Unlike many historical figures whose words have been analyzed for centuries, Grosser represents a modern perspective on opportunity and initiative. His philosophy rejects the passive waiting for lucky breaks or perfect timing that often delays achievement. Instead, he advocates for an entrepreneurial mindset that actively shapes circumstances and generates possibilities. This approach aligns with research in psychology and business that shows how successful individuals tend to create favorable conditions through networking, skill development, and strategic positioning rather than simply responding to existing opportunities. The quote encourages taking ownership of one's career and life trajectory by emphasizing that opportunities are constructed through vision, preparation, and deliberate action rather than encountered by chance.",
    image: "assets/grosser.jpeg",
  ),
  Quote(
    text: "Act as if what you do makes a difference. It does.",
    author: "William James",
    category: "Inspirational",
    details: "William James (1842-1910), an American philosopher and psychologist who helped establish Harvard's psychology department, was a pioneer of pragmatism and functionalism. This quote reflects his pragmatic philosophy that truth and meaning should be judged by their practical consequences. James developed theories about how beliefs and actions shape reality—ideas that would later influence fields from psychology to religious studies. His work 'The Varieties of Religious Experience' (1902) explored how personal beliefs affect one's experience of the world. This particular quote embodies his view that our actions have real consequences, regardless of our doubts about their significance. James suffered from depression throughout his life, making his emphasis on purposeful action particularly meaningful. His philosophy suggests that acting with purpose and conviction can transform both our experience and the world around us, creating a self-fulfilling cycle of meaningful impact.",
    image: "assets/james.jpeg",
  ),
  Quote(
    text: "Dream big and dare to fail.",
    author: "Norman Vaughan",
    category: "Motivational",
    details: "Norman Vaughan (1905-2005) lived an extraordinary life that embodied this adventurous philosophy. As a dog musher and explorer, he participated in Admiral Richard Byrd's first Antarctic expedition (1928-1930), where he helped establish the Little America base. In a remarkable demonstration of his own quote, at age 89, Vaughan led an expedition to climb and ski down Mount Vaughan in Antarctica—a 10,302-foot peak named after him. He succeeded in reaching the mountain but had to turn back before the summit due to weather conditions, exemplifying that the courage to attempt great things matters more than perfect success. Vaughan's remarkable longevity and continued adventures into his late 90s (including carrying the Olympic torch at age 94) demonstrated his lifelong commitment to ambitious dreams and bold action. His life reminds us that the willingness to risk failure is essential for achieving anything extraordinary.",
    image: "assets/vaughan.jpeg",
  ),
  Quote(
    text: "The secret of getting ahead is getting started.",
    author: "Mark Twain",
    category: "Success",
    details: "Mark Twain (1835-1910), born Samuel Clemens, was America's most famous humorist and one of its greatest novelists, creating classics like 'Adventures of Huckleberry Finn' and 'The Adventures of Tom Sawyer.' This quote reflects Twain's practical wisdom and understanding of human psychology. Twain knew firsthand about the challenges of beginning new ventures, having worked as a riverboat pilot, journalist, lecturer, entrepreneur, and author. He faced numerous personal and financial setbacks throughout his life but consistently reinvented himself through new initiatives. The quote addresses a universal human tendency toward procrastination and overthinking. Psychological research confirms Twain's insight that beginning a task is often the most difficult part of any process due to inertia and uncertainty. By emphasizing initiation over perfectionism, Twain captures an essential truth about productivity and achievement: momentum typically follows action rather than preceding it.",
    image: "assets/twain.jpeg",
  ),
  Quote(
    text: "Doubt kills more dreams than failure ever will.",
    author: "Suzy Kassem",
    category: "Inspirational",
    details: "Suzy Kassem is a contemporary American writer, poet, philosopher, and multi-disciplinary artist of Egyptian descent. This quote comes from her book 'Rise Up and Salute the Sun' (2010), a collection of philosophical writings and poetry. Kassem's work often explores themes of consciousness, spirituality, and human potential, drawing from both Eastern and Western philosophical traditions. This particular quote addresses the paralyzing effect of self-doubt, suggesting that internal barriers often prevent people from even attempting their dreams, whereas actual failure at least represents action and provides learning opportunities. Psychological research on fear of failure supports this insight, showing that anticipatory anxiety frequently leads to avoidance behaviors that prevent growth and achievement. Kassem's philosophy encourages embracing uncertainty and taking risks despite internal doubts, as the regret of inaction typically proves more painful than the lessons gained through attempted endeavors.",
    image: "assets/kassem.jpeg",
  ),
  Quote(
    text: "Do not go where the path may lead, go instead where there is no path and leave a trail.",
    author: "Ralph Waldo Emerson",
    category: "Life",
    details: "This quote epitomizes Ralph Waldo Emerson's (1803-1882) transcendentalist philosophy, which emphasized individualism, self-reliance, and novel thinking. As a lecturer, essayist, and poet, Emerson profoundly influenced American intellectual culture in the 19th century. His essay 'Self-Reliance' (1841) argued against conformity and for the courage to follow one's own convictions. Emerson practiced this philosophy by challenging established religious doctrines and cultural conventions of his time. He resigned from his position as a Unitarian minister to pursue a more individualistic spiritual and intellectual path. His home in Concord, Massachusetts became a gathering place for thinkers and writers like Henry David Thoreau, Bronson Alcott, and Margaret Fuller. This quote encourages not just personal authenticity but pioneering innovation—creating new possibilities rather than following established patterns. In doing so, Emerson articulates a distinctly American ideal of exploration and trailblazing that continues to inspire entrepreneurs, artists, and independent thinkers.",
    image: "assets/emerson.jpeg",
  ),
  Quote(
    text: "Life isn't about getting and having, it's about giving and being.",
    author: "Kevin Kruse",
    category: "Life",
    details: "Kevin Kruse is a contemporary American author, speaker, and entrepreneur focused on leadership, productivity, and employee engagement. As the founder of several multimillion-dollar companies and author of books like '15 Secrets Successful People Know About Time Management' and 'Employee Engagement 2.0,' Kruse brings both business experience and research to his philosophical outlook. This quote reflects his values-based approach to success that prioritizes contribution and authentic living over mere accumulation of wealth or possessions. Kruse's perspective aligns with research in positive psychology that consistently shows how materialism and wealth accumulation beyond basic needs contributes minimally to happiness, while purposeful activity, meaningful relationships, and generous giving correlate strongly with life satisfaction and well-being. His philosophy challenges conventional definitions of success based on acquisition and status, proposing instead that a meaningful life emerges from how we contribute to others and express our authentic selves.",
    image: "assets/kruse.jpeg",
  ),
];